In [1]:
import numpy as np
import cv2
from matplotlib import pyplot as plt

In [2]:
def ProcessImage1(im):
    resized = cv2.resize(im, (500,500))
    cv2.imshow("Resized", resized)
    cv2.waitKey(0)
    blurred = cv2.medianBlur(resized, 3)
    #image = cv2.cvtColor(blurred, cv2.COLOR_BGR2HSV)
    cv2.imshow("MedBlur", blurred)
    cv2.waitKey(0)
    return(blurred)

In [5]:
#k-means
def image_pp_segmentation(image2):
    image_before = image2
    image_f = np.array(image2)
    image = cv2.cvtColor(image2,cv2.COLOR_BGR2HSV)
    z = image.reshape((-1,3))
    Z = np.float32(z)
    cr = (cv2.TERM_CRITERIA_EPS+cv2.TERM_CRITERIA_MAX_ITER,10,1.0)
    k = 2
    ret,label,center = cv2.kmeans(Z,k,None,cr,10,cv2.KMEANS_RANDOM_CENTERS)

    center = np.uint8(center)
    res = center[label.flatten()]
    res = np.array(res)
    res2 = res.reshape((image.shape))

    mask = cv2.inRange(res2, (0,100,0), (173, 255, 170))
    imask = mask>0
    green = np.zeros_like(image,np.uint8)
    green[imask] = image[imask]

    image_or = cv2.bitwise_or(image, image, mask=mask)
    res3 = green
    for i in range(256):
        for j in range(256):
            for k in range(3):
               if ((res3[i][j][k] == 0 or res3[i][j][k] == 0 or res3[i][j][k] == 0)):
                    image_or[i][j][k]=0


    print("Center", center)
    
    
    cv2.imshow("res2", res2)
    cv2.waitKey(0)
    
    cv2.imshow("image", image)
    cv2.waitKey(0)
    
    cv2.imshow("image2", image2)
    cv2.waitKey(0)
    
    cv2.imshow("before", image_before)
    cv2.waitKey(0)
    
    cv2.imshow("image_or", image_or)
    cv2.waitKey(0)
    
    
    return image_or,res2,image,image2,image_before

In [6]:
img = cv2.imread('blackmeasles (1).jpg')

#gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
img1 = ProcessImage1(img)

image_pp_segmentation(img1)

#image = cv2.cvtColor(img1, cv2.COLOR_BGR2HSV)
#gray = cv2.cvtColor(image, cv2.COLOR_RGB2HSV)
#(T, threshInv) = cv2.threshold(image, 0, 255,cv2.THRESH_BINARY | cv2.THRESH_OTSU)
#_,thresh = cv2.threshold(image, np.mean(image), 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)

#cv2.imshow("Otsu", threshInv)
#cv2.waitKey(0)

Center [[  0   0   0]
 [ 64 163  68]]


(array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        ...,
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=uint8),
 array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 

-1

-1

error: OpenCV(4.5.4-dev) D:/a/opencv-python/opencv-python/opencv/modules/highgui/src/precomp.hpp:155: error: (-215:Assertion failed) src_depth != CV_16F && src_depth != CV_32S in function 'convertToShow'
